import { Analytics } from "@vercel/analytics/next"
import "../styles/globals.css";
import { Inter, Lora } from "next/font/google"
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

// Lora font family
const LoraFont = Lora({
  subsets: ['latin'],
  weight: ['600'],
  display: 'swap',
  variable: '--font-lora'
})

// Inter font family
const InterFont = Inter({

  subsets: ['latin'],
  weight: ['600'],
  display: 'swap',
  variable: '--font-inter'

})

export const metadata = {
  title: "Mohan Next.js App",
  description: "Portfolio site Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${InterFont.variable}`}>
      <body className={`antialiased`} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  );
}
