import Navbar from "@/components/Navbar";
import "./globals.css";
import { Playfair_Display } from "next/font/google"
import Footer from "@/components/Footer";

const PlayfairFont = Playfair_Display({
  subsets: ['latin'],
  weight: ['900'],
  display: 'swap',
  variable: '--font-playfair'
})

export const metadata = {
  title: "Mohan",
  description: "Portfolio site Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${PlayfairFont.variable}`}>
      <body className={`antialiased`} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  );
}
